CREATE DATABASE BD_CLIENTES;
GO
USE BD_CLIENTES;
CREATE TABLE Clientes (ClienteId INT IDENTITY PRIMARY KEY, Nombre NVARCHAR(120) NOT NULL);
CREATE TABLE ClientesDocumento (ClienteDocumentoId INT IDENTITY PRIMARY KEY, ClienteId INT NOT NULL REFERENCES Clientes(ClienteId), Numero NVARCHAR(20) NOT NULL);
